print('ini adalah py file yang baru')
print('langkah-langkah membuat file baru')
print('1. buka folder file berasal')
print('2. buat file py baru')
print('3. tulis kode program')
print('4. simpan file')
print('5. buka source control git CTRL+SHIFT+G')
print('6. stage changes dengan memiliih + pada file yang baru dibuat')
print('7. commit file dengan menulis pesan keterangan')
print('8. push file ke github dengan memilih icon titik tiga kemudian push')
print('periksa file di github apakah sudah terupload atau belum')
